# Generated by Django 4.2.4 on 2023-09-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='userInventory',
        ),
    ]
