# Generated by Django 4.2.3 on 2023-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_github_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='demolink',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
